# Generated by Django 4.1.5 on 2023-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact_contact_account_con_created_8bdae6_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user_from', 'user_to'), name='unique_contact'),
        ),
    ]
